### ISSUE TITLE
Any objection to implementing Standard/JSCS?

### ISSUE THREAD

**Issue by tbranyen** [workshopper/workshopper-exercise#32]
I'd like to contribute to this project, but the code style is a bit tedious to infer.  To avoid holding up PRs, should this project (and possibly all Workshoppers) implement [Standard](https://github.com/feross/standard) or [JSCS](http://jscs.info/)?

**Comment by martinheidegger** [comment]
@tbranyen I have been meaning to update it to `Standard` but I havn't had the time yet. PR welcome.
