### ISSUE TITLE
Exercises don't load on v2.5.2

### ISSUE THREAD

**Issue by denysdovhan** [workshopper/workshopper-exercise#37]
On `2.5.2` there is a problem with loading exercises. If I choose any language, English will load everytime. 

Look at this:

![image](https://cloud.githubusercontent.com/assets/3459374/10635927/d4bdf6ae-7804-11e5-9ede-3d8a4a613476.png)

Here are English exercise and Ukrainian footer (in learnyounode workshop).

There isn't the same problem on `2.5.0` and `2.5.1`.

**Comment by martinheidegger** [comment]
On it.

**Comment by denysdovhan** [comment]
I don't undestand.

**Comment by martinheidegger** [comment]
I am working on fixing it.

**Comment by denysdovhan** [comment]
ah, okay. I'm waiting.

**Comment by martinheidegger** [comment]
Should be fixed in 2.5.3

**Comment by denysdovhan** [comment]
Yep, all works fine.
Don't forget to update version in `package.json`.

**Comment by martinheidegger** [comment]
Do you mean of learnyounode? the version should work just fine as is

**Comment by denysdovhan** [comment]
Yes.
Nope, it doesn't work. `npm install` installs `workshopper-exercise@2.4.0` - just try it.
That's bcoz `~` means path versions. It should be replaced by a `^`.

**Comment by martinheidegger** [comment]
I understand what you mean. will do.

**Comment by denysdovhan** [comment]
i have pull request https://github.com/workshopper/learnyounode/pull/369
